version: 2.1
orbs:
  react: thefrontside/react@0.2.0

jobs:
  our_build:
    working_directory: ~/grapql_frontendPractice
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run: npm run build
      - run: echo "build done"

workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - our_build:
          requires:
            - react/install
