version: 2.1
orbs:
  react: thefrontside/react@0.2.0
workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react-building:
          requires:
            - react/install
          steps:
            - run: npm run build
            - run: echo "build done"
